### ISSUE TITLE
Focus can be lost from carousel after long press left / right 

### ISSUE THREAD

**Issue by brendanAx** [rdkcentral/Lightning-ui#13]
Steps to reproduce:

1. Run [UI components examples](https://github.com/mlapps/ui-component-examples) app with the latest version of `@lightningjs/ui` package installed (v1.2.2).
3. Open "Carousel displayed as Row" page.
4. Long press left/right for 1 - 2 seconds, then press right/left (the opposite direction) twice. It may be necessary to repeat this several times and alternate between long pressing left & right keys. E.g. long press right, left, left, long press left, right, right...

Result:
Focus is lost. It can be recovered by pressing up/down, but it's no longer possible to control the carousel until the page is refreshed.

The following error is visible in the console:
`Carousel.js:133 Uncaught TypeError: Cannot read properties of undefined (reading 'componentIndex')
  at StateMachineRouter.navigate (Carousel.js:133:58)
    at StateMachineRouter._attemptNavigation (CollectionWrapper.js:209:25)
    at StateMachineRouter.left (CollectionWrapper.js:184:21)
    at StateMachineRouter._handleLeft (CollectionWrapper.js:436:21)
    at StateMachineRouter.focusBottomUpEvent (lightning.js:13920:55)
    at StateMachineRouter._receiveKeydown (lightning.js:13943:48)
    at lightning.js:13736:26
    at _keydownListener (lightning.js:11415:17)`

This issue has been raised by the Metrological QA team for an app we are developing. It is a medium priority issue and has contributed to a delay in release of our app.

**Comment by jfboeve** [comment]
Hi Brendan,

Sorry for the inconvenience, this issue should be resolved with version 1.2.3. Thank you for reporting!
